#!/bin/bash

# ================= CONFIGURATION =================
# Source: Your compiled kernel tree (Where you ran make headers_install)
KERNEL_SRC="/home/rahulsnair/android/lineage/device/motorola/kernel-mtk"

# Destination: Your device tree headers folder
OUTPUT_DIR="/home/rahulsnair/android/lineage/device/motorola/cybert-kernel/headers"
# =================================================

echo "Starting UAPI & Kernel Header Extraction..."
echo "Source: $KERNEL_SRC"
echo "Target: $OUTPUT_DIR"

# 1. Safety Check: Did you generate the headers?
if [ ! -d "$KERNEL_SRC/usr/include/linux" ]; then
    echo "CRITICAL ERROR: 'usr/include/linux' not found!"
    echo "You must run the following in $KERNEL_SRC first:"
    echo "  make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- headers_install INSTALL_HDR_PATH=usr"
    exit 1
fi

mkdir -p "$OUTPUT_DIR"
cd "$KERNEL_SRC" || exit

# Helper function to copy headers (avoids copying C files)
sync_headers() {
    local src=$1
    local dest=$2
    
    if [ -d "$src" ]; then
        echo ">> Copying $src..."
        mkdir -p "$dest"
        # Flags: -a (archive), -v (verbose), -m (prune empty dirs)
        # We exclude .c, .o, .S, .cmd files to keep it clean and small
        rsync -avm \
            --include='*/' \
            --include='*.h' \
            --include='*.dtsi' \
            --exclude='*.c' \
            --exclude='*.o' \
            --exclude='*.S' \
            --exclude='*.cmd' \
            --exclude='Makefile' \
            --exclude='*' \
            "$src/" "$dest/"
    else
        echo "-- Skipping $src (Not found)"
    fi
}

# ---------------------------------------------------------
# PHASE 1: The "Clean" UAPI Headers (Most Important)
# ---------------------------------------------------------
# These are the sanitized headers generated by 'make headers_install'
# They go into usr/include in your device tree.
sync_headers "usr/include" "$OUTPUT_DIR/usr/include"

# ---------------------------------------------------------
# PHASE 2: Core Kernel Includes
# ---------------------------------------------------------
# Needed because some HALs incorrectly reference internal kernel headers
sync_headers "include" "$OUTPUT_DIR/include"

# ---------------------------------------------------------
# PHASE 3: Architecture Specific (ARM64/ARM Only)
# ---------------------------------------------------------
echo ">> Copying Architecture Headers..."
sync_headers "arch/arm64/include" "$OUTPUT_DIR/arch/arm64/include"
sync_headers "arch/arm/include"   "$OUTPUT_DIR/arch/arm/include"

# ---------------------------------------------------------
# PHASE 4: Vendor Drivers (MediaTek / Motorola Specifics)
# ---------------------------------------------------------
# This is where the magic happens for Audio, Display, and Wi-Fi
sync_headers "drivers"  "$OUTPUT_DIR/drivers"
sync_headers "techpack" "$OUTPUT_DIR/techpack"

# ---------------------------------------------------------
# PHASE 5: Subsystems (Crypto, FS, Lib, Security)
# ---------------------------------------------------------
sync_headers "crypto"           "$OUTPUT_DIR/crypto"
sync_headers "fs/unicode"       "$OUTPUT_DIR/fs/unicode"
sync_headers "lib"              "$OUTPUT_DIR/lib"
sync_headers "security/selinux" "$OUTPUT_DIR/security/selinux"
sync_headers "scripts"          "$OUTPUT_DIR/scripts"

# ---------------------------------------------------------
# PHASE 6: Cleanup
# ---------------------------------------------------------
echo ">> Cleaning up empty directories..."
find "$OUTPUT_DIR" -type d -empty -delete

echo "------------------------------------------------"
echo "Success! Headers populated."
echo "Location: $OUTPUT_DIR"
